batch_size: 1
num_workers: 12
infer_overlap: 0.6
learning_rate: 0.0001
max_epochs: 300
sw_batch_size: 2
val_every: 1
weight_decay: 0.00001
solver_name: Adam
loss_type: dice_ce
pretrained: False
resume: False
exp_name: SegUXNet-runs
seed: 123
colab: False
irl: False
sines: False
my_pc: True
new_max_epochs: None